# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Park.create(name: 'Bronx Park', borough: 'Bronx')
Park.create(name: 'Claremont Park', borough: 'Bronx')
Park.create(name: 'Crotona Park Bronx', borough: 'Bronx')
Park.create(name: 'Devoe Park Bronx', borough: 'Bronx')
Park.create(name: 'Ewen Park Bronx', borough: 'Bronx')
Park.create(name: 'Frank S. Hackett Park Dog Run', borough: 'Bronx')
Park.create(name: 'Franz Sigel Park', borough: 'Bronx')
Park.create(name: 'Henry Hudson Park', borough: 'Bronx')
Park.create(name: 'Joseph Rodham Drake Park', borough: 'Bronx')
Park.create(name: 'Macombs Dam Park', borough: 'Bronx')
Park.create(name: 'Mullaly Park', borough: 'Manhattan')
Park.create(name: 'Pelham Bay Park Bronx', borough: 'Bronx')
Park.create(name: 'Richman Echo Park', borough: ' Off-Leash/DogRuns_Type')
Park.create(name: 'Riverdale Park Bronx', borough: 'Bronx')
Park.create(name: 'Seton Park Dog Run', borough: 'Bronx')
Park.create(name: 'Siren Slope Park', borough: 'Bronx')
Park.create(name: 'Spuyten Duyvil Shorefront Park', borough: 'Bronx')
Park.create(name: 'Tremont Park Bronx', borough: 'Bronx')
Park.create(name: 'University Woods Park', borough: 'Bronx')
Park.create(name: 'Van Cortlandt Park Dog Run', borough: 'Bronx')
Park.create(name: 'Raoul Wallenberg Forest', borough: 'Bronx')
Park.create(name: 'Williamsbridge Oval', borough: 'Bronx')
Park.create(name: 'Asser Levy Park', borough: 'Brooklyn')
Park.create(name: 'Breukelen Ballfields', borough: 'Brooklyn')
Park.create(name: 'Brooklyn Bridge Park Dog Run', borough: ' Brooklyn')
Park.create(name: 'Brooklyn War Memorial', borough: 'Brooklyn')
Park.create(name: 'Canarsie Park', borough: 'Brooklyn')
Park.create(name: 'Cooper Park Dog Run', borough: 'Brooklyn')
Park.create(name: 'DiMattina Playground', borough: 'Brooklyn')
Park.create(name: 'Dyker Beach Park', borough: 'Brooklyn')
Park.create(name: 'Fort Greene Park', borough: 'Brooklyn')
Park.create(name: 'Friends Field', borough: 'Brooklyn')
Park.create(name: 'Fulton Park', borough: 'Brooklyn')
Park.create(name: 'Grand Ferry Park', borough: 'Brooklyn')
Park.create(name: 'Herbert Von King Park', borough: 'Brooklyn')
Park.create(name: 'Hillside Park Dog Run Brooklyn', borough: 'Brooklyn')
Park.create(name: 'John Paul Jones Park', borough: 'Brooklyn')
Park.create(name: 'Leon S Kaiser Playground', borough: 'Brooklyn')
Park.create(name: 'Leif Ericson Park & Square', borough: 'Brooklyn')
Park.create(name: 'Lincoln Terrace Park', borough: 'Brooklyn')
Park.create(name: 'Macri Triangle', borough: 'Brooklyn')
Park.create(name: 'Manhattan Beach Park', borough: 'Brooklyn')
Park.create(name: 'Marine Park', borough: 'Brooklyn')
Park.create(name: 'McCarren Park Dog Run', borough: 'Brooklyn')
Park.create(name: 'McGolrick Park Dog Run', borough: 'Brooklyn')
Park.create(name: 'McKinley Park', borough: 'Brooklyn')
Park.create(name: 'Mount Prospect Park', borough: 'Brooklyn')
Park.create(name: 'Owls Head Park Dog Run Brooklyn', borough: 'Brooklyn')
Park.create(name: 'Adam Yauch Park', borough: 'Brooklyn')
Park.create(name: 'Prospect Park', borough: 'Brooklyn')
Park.create(name: 'Shore Road Parks Conservancy', borough: 'Brooklyn')
Park.create(name: 'Sunset Park Brooklyn', borough: 'Brooklyn')
Park.create(name: 'Carl Schurz Park Dog Run', borough: 'Manhattan')
Park.create(name: 'Central Park', borough: 'Manhattan')
Park.create(name: 'Chelsea Waterside Park', borough: 'Manhattan')
Park.create(name: 'Coleman Field Manhattan', borough: 'Manhattan')
Park.create(name: 'De Witt Clinton Park', borough: 'Manhattan')
Park.create(name: 'East River Park Manhattan', borough: 'Manhattan')
Park.create(name: 'Fort Tryon Park', borough: 'Bronx')
Park.create(name: 'Ft. Washington Park', borough: 'Manhattan')
Park.create(name: 'Highbridge Park Manhattan', borough: 'Manhattan')
Park.create(name: 'Hudson River Park', borough: 'Manhattan')
Park.create(name: 'Inwood Hill Park', borough: 'Manhattan')
Park.create(name: 'J. Hood Wright Park', borough: 'Manhattan')
Park.create(name: 'Madison Square Park', borough: 'Manhattan')
Park.create(name: 'Marcus Garvey Park', borough: 'Manhattan')
Park.create(name: 'Morningside Park', borough: 'Manhattan')
Park.create(name: 'Peter Detmold Park', borough: 'Manhattan')
Park.create(name: 'Randalls Island Park', borough: 'Manhattan')
Park.create(name: 'Riverside Park Manhattan', borough: 'Manhattan')
Park.create(name: 'Robert Moses Park Playground', borough: 'Manhattan')
Park.create(name: 'St. Nicholas Park Manhattan', borough: 'Manhattan')
Park.create(name: 'Theodore Roosevelt Park', borough: 'Manhattan')
Park.create(name: 'Thomas Jefferson Park', borough: 'Manhattan')
Park.create(name: 'Tompkins Square Park', borough: 'Manhattan')
Park.create(name: 'Union Square Manhattan', borough: 'Manhattan')
Park.create(name: 'Washington Square Park', borough: 'Manhattan')
Park.create(name: 'Alley Pond Park', borough: 'Manhattan')
Park.create(name: 'Astoria Park', borough: 'Queens')
Park.create(name: 'Baisley Pond Park', borough: 'Queens')
Park.create(name: 'Bayswater Park', borough: 'Queens')
Park.create(name: 'Crocheron Park Queens', borough: 'Queens')
Park.create(name: 'Cunningham Park', borough: 'Queens')
Park.create(name: 'Flushing Meadows Corona Park', borough: 'Queens')
Park.create(name: 'Forest Park Queens', borough: 'Queens')
Park.create(name: 'Juniper Valley Park', borough: 'Queens')
Park.create(name: 'Little Bay Park', borough: 'Queens')
Park.create(name: 'MacNeil Park', borough: 'Queens')
Park.create(name: 'Murray Playground Queens', borough: 'Queens')
Park.create(name: 'Queensbridge Park', borough: 'Queens')
Park.create(name: 'Rainey Park', borough: 'Queens')
Park.create(name: 'Ralph DeMarco Park', borough: 'Queens')
Park.create(name: 'Rockaway Community Park', borough: 'Queens')
Park.create(name: 'Rockaway Freeway', borough: 'Queens')
Park.create(name: 'Sherry Park', borough: 'Queens')
Park.create(name: 'Springfield Park', borough: 'Queens')
Park.create(name: 'Lawrence Virgilio Playground', borough: 'Queens')
Park.create(name: 'Yellowstone Park', borough: 'Queens')
Park.create(name: 'Allison Park Queens', borough: 'Queens')
Park.create(name: 'Arthur Von Briesen Park', borough: 'Staten Island')
Park.create(name: 'Clove Lakes Park', borough: 'Staten Island')
Park.create(name: 'Conference House Park', borough: 'Staten Island')
Park.create(name: 'Crescent Beach Park', borough: 'Staten Island')
Park.create(name: 'Evergreen Park', borough: 'Staten Island')
Park.create(name: 'Father Macris Park', borough: 'Staten Island')
Park.create(name: 'Lemon Creek Park Staten Island', borough: 'Staten Island')
Park.create(name: 'Ocean Breeze Park Staten Island', borough: 'Staten Island')
Park.create(name: 'Silver Lake Park', borough: 'Staten Island')
Park.create(name: 'South Beach Park', borough: 'Staten Island')
Park.create(name: 'Willowbrook Park', borough: 'Staten Island')
Park.create(name: 'Wolfe''s Pond Park Staten Island', borough: 'Staten Island')
Park.create(name: 'Clove Lakes Park', borough: 'Staten Island')
Park.create(name: 'Coffey Park', borough: 'Brooklyn')
Park.create(name: 'Corlears Hook Park', borough: 'Manhattan')
Park.create(name: 'Bobby Wagner Walk', borough: 'Manhattan')
Park.create(name: 'Bloomingdale Park', borough: 'Staten Island')
